export const SET_SELECTED_TILESET = "SET_SELECTED_TILESET";
export const SET_SELECTED_TILE = "SET_SELECTED_TILE";
export const ADD_COLOR = "ADD_COLOR";
export const REMOVE_COLOR = "REMOVE_COLOR";
export const SET_SELECTED_COLOR = "SET_SELECTED_COLOR";
