export const SET_SELECTED_TILESET = "SET_SELECTED_TILESET";
export const SET_SELECTED_TILE = "SET_SELECTED_TILE";

export const SET_SELECTED_COLOR = "SET_SELECTED_COLOR";
export const SET_PIXEL_DATA = "SET_PIXEL_DATA";
